version: '3.1'

services:
  web_api:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/app
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example123
    ports:
      - "5432:5432"
